In [1]:
from pycaret.datasets import get_data
data = get_data('income')

,age,workclass,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income >50K
0,39,State-gov,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,0
1,50,Self-emp-not-inc,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,0
2,38,Private,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,0
3,53,Private,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,0
4,28,Private,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,0

In [3]:
import pandas as pd
data = pd.get_dummies(data)
data.head()

,age,education-num,capital-gain,capital-loss,hours-per-week,income >50K,workclass_ Federal-gov,workclass_ Local-gov,workclass_ Never-worked,workclass_ Private,...,native-country_ Portugal,native-country_ Puerto-Rico,native-country_ Scotland,native-country_ South,native-country_ Taiwan,native-country_ Thailand,native-country_ Trinadad&Tobago,native-country_ United-States,native-country_ Vietnam,native-country_ Yugoslavia
0,39,13,2174,0,40,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
1,50,13,0,0,13,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
2,38,9,0,0,40,0,0,0,0,1,...,0,0,0,0,0,0,0,1,0,0
3,53,7,0,0,40,0,0,0,0,1,...,0,0,0,0,0,0,0,1,0,0
4,28,13,0,0,40,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0

In [4]:
from pycaret.classification import *

In [6]:
s = setup(data, target='income >50K', session_id=786)

Setup Succesfully Completed!

## Compare Models

In [8]:
%%time
compare_models()

Wall time: 5min 27s

## Blend Models

In [9]:
%%time
b1 = blend_models()

      Accuracy  AUC  Recall   Prec.      F1   Kappa
0       0.8645  0.0  0.5701  0.8109  0.6695  0.5875
1       0.8697  0.0  0.5938  0.8150  0.6870  0.6073
2       0.8640  0.0  0.5993  0.7852  0.6798  0.5954
3       0.8666  0.0  0.5974  0.7981  0.6833  0.6010
4       0.8706  0.0  0.5920  0.8207  0.6878  0.6089
5       0.8662  0.0  0.6066  0.7891  0.6859  0.6027
6       0.8692  0.0  0.6011  0.8068  0.6889  0.6084
7       0.8499  0.0  0.5410  0.7674  0.6346  0.5437
8       0.8578  0.0  0.5774  0.7751  0.6618  0.5742
9       0.8670  0.0  0.5912  0.8040  0.6814  0.5998
Mean    0.8646  0.0  0.5870  0.7972  0.6760  0.5929
SD      0.0060  0.0  0.0185  0.0167  0.0161  0.0193

Wall time: 2min 57s